<a href="https://colab.research.google.com/github/augustiner-nyc/SUPERVISED-MACHINE-LEARNING/blob/main/3.3%20Logistic%20Regression%20in%20Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Librariers
import sklearn
import numpy as np
import pandas as pd

In [10]:
#Load the Data
from sklearn.datasets import load_iris
iris = load_iris()
X = pd.DataFrame(iris.data, columns = iris.feature_names)
y = iris.target

In [11]:
#Split the Data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [14]:
#Train the model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', multi_class ='multinomial')
model.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(multi_class='multinomial')

In [15]:
#Test the model
from sklearn.metrics import confusion_matrix
y_predict = model.predict(X_test)
confusion_matrix(y_test, y_predict)

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]])

In [16]:
#Capture Accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predict)*100

97.36842105263158

In [17]:
#Intercepts and Coefficients
model.intercept_, model.coef_

(array([  9.32961712,   1.45027229, -10.77988942]),
 array([[-0.43046154,  0.80218829, -2.30480834, -0.95069252],
        [ 0.62801078, -0.42397165, -0.20547615, -0.78338625],
        [-0.19754924, -0.37821665,  2.51028449,  1.73407877]]))