<a href="https://colab.research.google.com/github/augustiner-nyc/SUPERVISED-MACHINE-LEARNING/blob/main/3.1%20Support%20Vector%20Machines%20in%20Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Support Vector Machines in Python

In [4]:
# Import Libraries
import sklearn
from sklearn import svm
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import mlxtend

In [2]:
# Load the Data
from sklearn.datasets import load_iris
iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = iris.target

In [3]:
# Split the Data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [5]:
# Train the model
model = svm.SVC(kernel='linear')
model.fit(X_train,y_train)

SVC(kernel='linear')

In [7]:
# Test the model
from sklearn.metrics import confusion_matrix
# Test result
y_predict = model.predict(X_test)
confusion_matrix(y_test, y_predict)

array([[13,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  9]])

In [8]:
# Check the Accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predict)*100

100.0

In [9]:
# Get the number of Support vectors for each class
model.n_support_

array([ 3, 10, 10], dtype=int32)

# SVM Using Sklearn - ploy


In [10]:
# Fit the model
clf = svm.SVC(kernel='poly', degree=3)
clf.fit(X_train, y_train)

SVC(kernel='poly')

In [11]:
# Test the model
y_predict = clf.predict(X_test)
confusion_matrix(y_test, y_predict)

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]])

In [12]:
# Check the accuracy
accuracy_score(y_test, y_predict)*100

97.36842105263158

# SVM in Python for Classification using sklearn - rbf

In [15]:
# Rain the model
clf = svm.SVC(kernel='rbf', gamma=.3)
clf.fit(X_train, y_train)

SVC(gamma=0.3)

In [14]:
# Test the model
y_predict = clf.predict(X_test)
confusion_matrix(y_test, y_predict)

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]])

In [13]:
# Check the accuracy
accuracy_score(y_test, y_predict)*100

97.36842105263158

# Grid Search SVM Method using GridsearchCV

In [16]:
from sklearn.model_selection import GridSearchCV
parameters = {'kernel':('linear', 'rbf', 'poly'), 'C':[0.1, 0.5, 1, 10], 'degree':[2,3,4]}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters, cv=5)
clf.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 0.5, 1, 10], 'degree': [2, 3, 4],
                         'kernel': ('linear', 'rbf', 'poly')})

In [17]:
# Select the Best Method and Parameters
clf.best_params_

{'C': 0.1, 'degree': 3, 'kernel': 'poly'}